package sarandon.decotheco.thecoradores.bean;
// Generated 30-jul-2017 23:22:48 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AuxTypesStates generated by hbm2java
 */
@Entity
@Table(name = "aux_types_states", catalog = "decotheco")
public class AuxTypesStates implements java.io.Serializable {

	private AuxTypesStatesId id;
	private ProjectsStates projectsStates;
	private ProjectsTypes projectsTypes;
	private Integer nextState;

	public AuxTypesStates() {
	}

	public AuxTypesStates(AuxTypesStatesId id, ProjectsStates projectsStates, ProjectsTypes projectsTypes) {
		this.id = id;
		this.projectsStates = projectsStates;
		this.projectsTypes = projectsTypes;
	}

	public AuxTypesStates(AuxTypesStatesId id, ProjectsStates projectsStates, ProjectsTypes projectsTypes,
			Integer nextState) {
		this.id = id;
		this.projectsStates = projectsStates;
		this.projectsTypes = projectsTypes;
		this.nextState = nextState;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idType", column = @Column(name = "id_type", nullable = false)),
			@AttributeOverride(name = "idState", column = @Column(name = "id_state", nullable = false)) })
	public AuxTypesStatesId getId() {
		return this.id;
	}

	public void setId(AuxTypesStatesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_state", nullable = false, insertable = false, updatable = false)
	public ProjectsStates getProjectsStates() {
		return this.projectsStates;
	}

	public void setProjectsStates(ProjectsStates projectsStates) {
		this.projectsStates = projectsStates;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type", nullable = false, insertable = false, updatable = false)
	public ProjectsTypes getProjectsTypes() {
		return this.projectsTypes;
	}

	public void setProjectsTypes(ProjectsTypes projectsTypes) {
		this.projectsTypes = projectsTypes;
	}

	@Column(name = "next_state")
	public Integer getNextState() {
		return this.nextState;
	}

	public void setNextState(Integer nextState) {
		this.nextState = nextState;
	}

}
