package sarandon.decotheco.thecoradores.bean;
// Generated 30-jul-2017 23:22:48 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuxTypesStatesId generated by hbm2java
 */
@Embeddable
public class AuxTypesStatesId implements java.io.Serializable {

	private int idType;
	private int idState;

	public AuxTypesStatesId() {
	}

	public AuxTypesStatesId(int idType, int idState) {
		this.idType = idType;
		this.idState = idState;
	}

	@Column(name = "id_type", nullable = false)
	public int getIdType() {
		return this.idType;
	}

	public void setIdType(int idType) {
		this.idType = idType;
	}

	@Column(name = "id_state", nullable = false)
	public int getIdState() {
		return this.idState;
	}

	public void setIdState(int idState) {
		this.idState = idState;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuxTypesStatesId))
			return false;
		AuxTypesStatesId castOther = (AuxTypesStatesId) other;

		return (this.getIdType() == castOther.getIdType()) && (this.getIdState() == castOther.getIdState());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdType();
		result = 37 * result + this.getIdState();
		return result;
	}

}
