package sarandon.decotheco.thecoradores.bean;
// Generated 16-abr-2017 9:59:59 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Imagenes generated by hbm2java
 */
@Entity
@Table(name = "imagenes", catalog = "decotheco")
public class Imagenes implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String estilo;
	private String color;
	private String minimalismo;
	private String habitacion;

	public Imagenes() {
	}

	public Imagenes(String nombre, String estilo, String color, String minimalismo, String habitacion) {
		this.nombre = nombre;
		this.estilo = estilo;
		this.color = color;
		this.minimalismo = minimalismo;
		this.habitacion = habitacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 512)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estilo", length = 45)
	public String getEstilo() {
		return this.estilo;
	}

	public void setEstilo(String estilo) {
		this.estilo = estilo;
	}

	@Column(name = "color", length = 45)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "minimalismo", length = 45)
	public String getMinimalismo() {
		return this.minimalismo;
	}

	public void setMinimalismo(String minimalismo) {
		this.minimalismo = minimalismo;
	}

	@Column(name = "habitacion", length = 45)
	public String getHabitacion() {
		return this.habitacion;
	}

	public void setHabitacion(String habitacion) {
		this.habitacion = habitacion;
	}

}
