package sarandon.decotheco.thecoradores.bean;
// Generated 16-abr-2017 9:59:59 by Hibernate Tools 5.2.1.Final

import java.util.ArrayList;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;

import sarandon.assistance.servlet.more.dataBBDD;

/**
 * Information generated by hbm2java
 */
@Entity
@Table(name = "information", catalog = "decotheco", uniqueConstraints = @UniqueConstraint(columnNames = "id_proyecto"))
public class Information implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Projects projects;
	private String habitacion;
	private String enMente;
	private Integer prioridad1;
	private Integer prioridad2;
	private Date fechaIngreso;
	private Integer prioridad3;
	private Integer prioridad4;
	private Integer prioridad5;
	private Integer prioridad6;
	private String inspiracion1;
	private String inspiracion2;
	private String inspiracion3;
	private Integer usos1;
	private Integer usos2;
	private Integer usos3;
	private Integer usos4;
	private Integer usos5;
	private Integer usos6;
	private Integer asientos1;
	private Integer asientos2;
	private Integer asientos3;
	private Integer asientos4;
	private Integer asientos5;
	private Integer asientos6;
	private Integer auxiliares1;
	private Integer auxiliares2;
	private Integer auxiliares3;
	private Integer auxiliares4;
	private Integer auxiliares5;
	private Integer almacenaje1;
	private Integer almacenaje2;
	private Integer almacenaje3;
	private Integer almacenaje4;
	private Integer almacenaje5;
	private Integer deco1;
	private Integer deco2;
	private Integer deco3;
	private Integer deco4;
	private Integer deco5;
	private String elementosExtra;
	private String imprescindiblesUrl1;
	private String imprescindiblesUrl2;
	private String imprescindiblesUrl3;
	private String otraNecesidad;
	private String diy1;
	private String diy2;
	private String diy3;
	private Integer suelo;
	private Integer pintura;
	private String noQuiero;
	private String medidasAncho;
	private String medidasAlto;
	private String presupuesto;
	private Integer valida;
	private String extraOtrasCosas;
	private Integer ventanas1;
	private Integer ventanas2;
	private Integer ventanas3;
	
	
	public ArrayList<String> filesInspiraciones= new ArrayList<String>(0);
	public ArrayList<String> filesEsapcio= new ArrayList<String>(0);
	public ArrayList<String> filesPlanos= new ArrayList<String>(0);
	public ArrayList<String> filesMuebles= new ArrayList<String>(0);
	

	public Information() {
	}

	public Information(Projects projects, String habitacion, String enMente, Integer prioridad1, Integer prioridad2,
			Date fechaIngreso, Integer prioridad3, Integer prioridad4, Integer prioridad5, Integer prioridad6,
			String inspiracion1, String inspiracion2, String inspiracion3, Integer usos1, Integer usos2, Integer usos3,
			Integer usos4, Integer usos5, Integer usos6, Integer asientos1, Integer asientos2, Integer asientos3,
			Integer asientos4, Integer asientos5, Integer asientos6, Integer auxiliares1, Integer auxiliares2,
			Integer auxiliares3, Integer auxiliares4, Integer auxiliares5, Integer almacenaje1, Integer almacenaje2,
			Integer almacenaje3, Integer almacenaje4, Integer almacenaje5, Integer deco1, Integer deco2, Integer deco3,
			Integer deco4, Integer deco5, String elementosExtra, String imprescindiblesUrl1, String imprescindiblesUrl2,
			String imprescindiblesUrl3, String otraNecesidad, String diy1, String diy2, String diy3, Integer suelo,
			Integer pintura, String noQuiero, String medidasAncho, String medidasAlto, String presupuesto,
			Integer valida, String extraOtrasCosas, Integer ventanas1, Integer ventanas2, Integer ventanas3) {
		this.projects = projects;
		this.habitacion = habitacion;
		this.enMente = enMente;
		this.prioridad1 = prioridad1;
		this.prioridad2 = prioridad2;
		this.fechaIngreso = fechaIngreso;
		this.prioridad3 = prioridad3;
		this.prioridad4 = prioridad4;
		this.prioridad5 = prioridad5;
		this.prioridad6 = prioridad6;
		this.inspiracion1 = inspiracion1;
		this.inspiracion2 = inspiracion2;
		this.inspiracion3 = inspiracion3;
		this.usos1 = usos1;
		this.usos2 = usos2;
		this.usos3 = usos3;
		this.usos4 = usos4;
		this.usos5 = usos5;
		this.usos6 = usos6;
		this.asientos1 = asientos1;
		this.asientos2 = asientos2;
		this.asientos3 = asientos3;
		this.asientos4 = asientos4;
		this.asientos5 = asientos5;
		this.asientos6 = asientos6;
		this.auxiliares1 = auxiliares1;
		this.auxiliares2 = auxiliares2;
		this.auxiliares3 = auxiliares3;
		this.auxiliares4 = auxiliares4;
		this.auxiliares5 = auxiliares5;
		this.almacenaje1 = almacenaje1;
		this.almacenaje2 = almacenaje2;
		this.almacenaje3 = almacenaje3;
		this.almacenaje4 = almacenaje4;
		this.almacenaje5 = almacenaje5;
		this.deco1 = deco1;
		this.deco2 = deco2;
		this.deco3 = deco3;
		this.deco4 = deco4;
		this.deco5 = deco5;
		this.elementosExtra = elementosExtra;
		this.imprescindiblesUrl1 = imprescindiblesUrl1;
		this.imprescindiblesUrl2 = imprescindiblesUrl2;
		this.imprescindiblesUrl3 = imprescindiblesUrl3;
		this.otraNecesidad = otraNecesidad;
		this.diy1 = diy1;
		this.diy2 = diy2;
		this.diy3 = diy3;
		this.suelo = suelo;
		this.pintura = pintura;
		this.noQuiero = noQuiero;
		this.medidasAncho = medidasAncho;
		this.medidasAlto = medidasAlto;
		this.presupuesto = presupuesto;
		this.valida = valida;
		this.extraOtrasCosas = extraOtrasCosas;
		this.ventanas1 = ventanas1;
		this.ventanas2 = ventanas2;
		this.ventanas3 = ventanas3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proyecto", unique = true)
	@JsonBackReference
	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	@Column(name = "habitacion", length = 45)
	public String getHabitacion() {
		return this.habitacion;
	}

	public void setHabitacion(String habitacion) {
		this.habitacion = habitacion;
	}

	@Column(name = "en_mente", length = 2048)
	public String getEnMente() {
		return this.enMente;
	}

	public void setEnMente(String enMente) {
		this.enMente = enMente;
	}

	@Column(name = "prioridad_1")
	public Integer getPrioridad1() {
		return this.prioridad1;
	}

	public void setPrioridad1(Integer prioridad1) {
		this.prioridad1 = prioridad1;
	}

	@Column(name = "prioridad_2")
	public Integer getPrioridad2() {
		return this.prioridad2;
	}

	public void setPrioridad2(Integer prioridad2) {
		this.prioridad2 = prioridad2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_ingreso", length = 0)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "prioridad_3")
	public Integer getPrioridad3() {
		return this.prioridad3;
	}

	public void setPrioridad3(Integer prioridad3) {
		this.prioridad3 = prioridad3;
	}

	@Column(name = "prioridad_4")
	public Integer getPrioridad4() {
		return this.prioridad4;
	}

	public void setPrioridad4(Integer prioridad4) {
		this.prioridad4 = prioridad4;
	}

	@Column(name = "prioridad_5")
	public Integer getPrioridad5() {
		return this.prioridad5;
	}

	public void setPrioridad5(Integer prioridad5) {
		this.prioridad5 = prioridad5;
	}

	@Column(name = "prioridad_6")
	public Integer getPrioridad6() {
		return this.prioridad6;
	}

	public void setPrioridad6(Integer prioridad6) {
		this.prioridad6 = prioridad6;
	}

	@Column(name = "inspiracion_1", length = 1024)
	public String getInspiracion1() {
		return this.inspiracion1;
	}

	public void setInspiracion1(String inspiracion1) {
		this.inspiracion1 = inspiracion1;
	}

	@Column(name = "inspiracion_2", length = 1024)
	public String getInspiracion2() {
		return this.inspiracion2;
	}

	public void setInspiracion2(String inspiracion2) {
		this.inspiracion2 = inspiracion2;
	}

	@Column(name = "inspiracion_3", length = 1024)
	public String getInspiracion3() {
		return this.inspiracion3;
	}

	public void setInspiracion3(String inspiracion3) {
		this.inspiracion3 = inspiracion3;
	}

	@Column(name = "usos_1")
	public Integer getUsos1() {
		return this.usos1;
	}

	public void setUsos1(Integer usos1) {
		this.usos1 = usos1;
	}

	@Column(name = "usos_2")
	public Integer getUsos2() {
		return this.usos2;
	}

	public void setUsos2(Integer usos2) {
		this.usos2 = usos2;
	}

	@Column(name = "usos_3")
	public Integer getUsos3() {
		return this.usos3;
	}

	public void setUsos3(Integer usos3) {
		this.usos3 = usos3;
	}

	@Column(name = "usos_4")
	public Integer getUsos4() {
		return this.usos4;
	}

	public void setUsos4(Integer usos4) {
		this.usos4 = usos4;
	}

	@Column(name = "usos_5")
	public Integer getUsos5() {
		return this.usos5;
	}

	public void setUsos5(Integer usos5) {
		this.usos5 = usos5;
	}

	@Column(name = "usos_6")
	public Integer getUsos6() {
		return this.usos6;
	}

	public void setUsos6(Integer usos6) {
		this.usos6 = usos6;
	}

	@Column(name = "asientos_1")
	public Integer getAsientos1() {
		return this.asientos1;
	}

	public void setAsientos1(Integer asientos1) {
		this.asientos1 = asientos1;
	}

	@Column(name = "asientos_2")
	public Integer getAsientos2() {
		return this.asientos2;
	}

	public void setAsientos2(Integer asientos2) {
		this.asientos2 = asientos2;
	}

	@Column(name = "asientos_3")
	public Integer getAsientos3() {
		return this.asientos3;
	}

	public void setAsientos3(Integer asientos3) {
		this.asientos3 = asientos3;
	}

	@Column(name = "asientos_4")
	public Integer getAsientos4() {
		return this.asientos4;
	}

	public void setAsientos4(Integer asientos4) {
		this.asientos4 = asientos4;
	}

	@Column(name = "asientos_5")
	public Integer getAsientos5() {
		return this.asientos5;
	}

	public void setAsientos5(Integer asientos5) {
		this.asientos5 = asientos5;
	}

	@Column(name = "asientos_6")
	public Integer getAsientos6() {
		return this.asientos6;
	}

	public void setAsientos6(Integer asientos6) {
		this.asientos6 = asientos6;
	}

	@Column(name = "auxiliares_1")
	public Integer getAuxiliares1() {
		return this.auxiliares1;
	}

	public void setAuxiliares1(Integer auxiliares1) {
		this.auxiliares1 = auxiliares1;
	}

	@Column(name = "auxiliares_2")
	public Integer getAuxiliares2() {
		return this.auxiliares2;
	}

	public void setAuxiliares2(Integer auxiliares2) {
		this.auxiliares2 = auxiliares2;
	}

	@Column(name = "auxiliares_3")
	public Integer getAuxiliares3() {
		return this.auxiliares3;
	}

	public void setAuxiliares3(Integer auxiliares3) {
		this.auxiliares3 = auxiliares3;
	}

	@Column(name = "auxiliares_4")
	public Integer getAuxiliares4() {
		return this.auxiliares4;
	}

	public void setAuxiliares4(Integer auxiliares4) {
		this.auxiliares4 = auxiliares4;
	}

	@Column(name = "auxiliares_5")
	public Integer getAuxiliares5() {
		return this.auxiliares5;
	}

	public void setAuxiliares5(Integer auxiliares5) {
		this.auxiliares5 = auxiliares5;
	}

	@Column(name = "almacenaje_1")
	public Integer getAlmacenaje1() {
		return this.almacenaje1;
	}

	public void setAlmacenaje1(Integer almacenaje1) {
		this.almacenaje1 = almacenaje1;
	}

	@Column(name = "almacenaje_2")
	public Integer getAlmacenaje2() {
		return this.almacenaje2;
	}

	public void setAlmacenaje2(Integer almacenaje2) {
		this.almacenaje2 = almacenaje2;
	}

	@Column(name = "almacenaje_3")
	public Integer getAlmacenaje3() {
		return this.almacenaje3;
	}

	public void setAlmacenaje3(Integer almacenaje3) {
		this.almacenaje3 = almacenaje3;
	}

	@Column(name = "almacenaje_4")
	public Integer getAlmacenaje4() {
		return this.almacenaje4;
	}

	public void setAlmacenaje4(Integer almacenaje4) {
		this.almacenaje4 = almacenaje4;
	}

	@Column(name = "almacenaje_5")
	public Integer getAlmacenaje5() {
		return this.almacenaje5;
	}

	public void setAlmacenaje5(Integer almacenaje5) {
		this.almacenaje5 = almacenaje5;
	}

	@Column(name = "deco_1")
	public Integer getDeco1() {
		return this.deco1;
	}

	public void setDeco1(Integer deco1) {
		this.deco1 = deco1;
	}

	@Column(name = "deco_2")
	public Integer getDeco2() {
		return this.deco2;
	}

	public void setDeco2(Integer deco2) {
		this.deco2 = deco2;
	}

	@Column(name = "deco_3")
	public Integer getDeco3() {
		return this.deco3;
	}

	public void setDeco3(Integer deco3) {
		this.deco3 = deco3;
	}

	@Column(name = "deco_4")
	public Integer getDeco4() {
		return this.deco4;
	}

	public void setDeco4(Integer deco4) {
		this.deco4 = deco4;
	}

	@Column(name = "deco_5")
	public Integer getDeco5() {
		return this.deco5;
	}

	public void setDeco5(Integer deco5) {
		this.deco5 = deco5;
	}

	@Column(name = "elementos_extra", length = 1024)
	public String getElementosExtra() {
		return this.elementosExtra;
	}

	public void setElementosExtra(String elementosExtra) {
		this.elementosExtra = elementosExtra;
	}

	@Column(name = "imprescindibles_url_1", length = 1024)
	public String getImprescindiblesUrl1() {
		return this.imprescindiblesUrl1;
	}

	public void setImprescindiblesUrl1(String imprescindiblesUrl1) {
		this.imprescindiblesUrl1 = imprescindiblesUrl1;
	}

	@Column(name = "imprescindibles_url_2", length = 1024)
	public String getImprescindiblesUrl2() {
		return this.imprescindiblesUrl2;
	}

	public void setImprescindiblesUrl2(String imprescindiblesUrl2) {
		this.imprescindiblesUrl2 = imprescindiblesUrl2;
	}

	@Column(name = "imprescindibles_url_3", length = 1024)
	public String getImprescindiblesUrl3() {
		return this.imprescindiblesUrl3;
	}

	public void setImprescindiblesUrl3(String imprescindiblesUrl3) {
		this.imprescindiblesUrl3 = imprescindiblesUrl3;
	}

	@Column(name = "otra_necesidad", length = 2014)
	public String getOtraNecesidad() {
		return this.otraNecesidad;
	}

	public void setOtraNecesidad(String otraNecesidad) {
		this.otraNecesidad = otraNecesidad;
	}

	@Column(name = "diy_1", length = 2014)
	public String getDiy1() {
		return this.diy1;
	}

	public void setDiy1(String diy1) {
		this.diy1 = diy1;
	}

	@Column(name = "diy_2", length = 2014)
	public String getDiy2() {
		return this.diy2;
	}

	public void setDiy2(String diy2) {
		this.diy2 = diy2;
	}

	@Column(name = "diy_3", length = 2014)
	public String getDiy3() {
		return this.diy3;
	}

	public void setDiy3(String diy3) {
		this.diy3 = diy3;
	}

	@Column(name = "suelo")
	public Integer getSuelo() {
		return this.suelo;
	}

	public void setSuelo(Integer suelo) {
		this.suelo = suelo;
	}

	@Column(name = "pintura")
	public Integer getPintura() {
		return this.pintura;
	}

	public void setPintura(Integer pintura) {
		this.pintura = pintura;
	}

	@Column(name = "no_quiero", length = 2014)
	public String getNoQuiero() {
		return this.noQuiero;
	}

	public void setNoQuiero(String noQuiero) {
		this.noQuiero = noQuiero;
	}

	@Column(name = "medidas_ancho", length = 45)
	public String getMedidasAncho() {
		return this.medidasAncho;
	}

	public void setMedidasAncho(String medidasAncho) {
		this.medidasAncho = medidasAncho;
	}

	@Column(name = "medidas_alto", length = 45)
	public String getMedidasAlto() {
		return this.medidasAlto;
	}

	public void setMedidasAlto(String medidasAlto) {
		this.medidasAlto = medidasAlto;
	}

	@Column(name = "presupuesto", length = 45)
	public String getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(String presupuesto) {
		this.presupuesto = presupuesto;
	}

	@Column(name = "valida")
	public Integer getValida() {
		return this.valida;
	}

	public void setValida(Integer valida) {
		this.valida = valida;
	}

	@Column(name = "extra_otras_cosas", length = 4048)
	public String getExtraOtrasCosas() {
		return this.extraOtrasCosas;
	}

	public void setExtraOtrasCosas(String extraOtrasCosas) {
		this.extraOtrasCosas = extraOtrasCosas;
	}

	@Column(name = "ventanas_1")
	public Integer getVentanas1() {
		return this.ventanas1;
	}

	public void setVentanas1(Integer ventanas1) {
		this.ventanas1 = ventanas1;
	}

	@Column(name = "ventanas_2")
	public Integer getVentanas2() {
		return this.ventanas2;
	}

	public void setVentanas2(Integer ventanas2) {
		this.ventanas2 = ventanas2;
	}

	@Column(name = "ventanas_3")
	public Integer getVentanas3() {
		return this.ventanas3;
	}

	public void setVentanas3(Integer ventanas3) {
		this.ventanas3 = ventanas3;
	}
	
	public void setFiles(String path){
		dataBBDD db= new dataBBDD();
		this.filesInspiraciones = db.getFiles(
				projects.getUsers().getMail(),
				projects.getNombreProyecto(),
				"inspiraciones", path);
		this.filesEsapcio = db.getFiles(
				projects.getUsers().getMail(),
				projects.getNombreProyecto(),
				"espacios", path);
		this.filesPlanos = db.getFiles(
				projects.getUsers().getMail(),
				projects.getNombreProyecto(),
				"plano", path);
		this.filesMuebles = db.getFiles(
				projects.getUsers().getMail(),
				projects.getNombreProyecto(),
				"muebles", path);
	}

}
