package sarandon.decotheco.thecoradores.bean;
// Generated 16-abr-2017 9:59:59 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Pagos generated by hbm2java
 */
@Entity
@Table(name = "pagos", catalog = "decotheco", uniqueConstraints = @UniqueConstraint(columnNames = "regalo_id"))
public class Pagos implements java.io.Serializable {

	private Integer id;
	private Projects projects;
	private Regalos regalos;
	private Float total;
	private String concepto;
	private Date fechaingreso;
	private String codigo;

	public Pagos() {
	}

	public Pagos(Projects projects, Regalos regalos, Float total, String concepto, Date fechaingreso, String codigo) {
		this.projects = projects;
		this.regalos = regalos;
		this.total = total;
		this.concepto = concepto;
		this.fechaingreso = fechaingreso;
		this.codigo = codigo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	@JsonBackReference
	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "regalo_id", unique = true)
	@JsonBackReference
	public Regalos getRegalos() {
		return this.regalos;
	}

	public void setRegalos(Regalos regalos) {
		this.regalos = regalos;
	}

	@Column(name = "total", precision = 12, scale = 0)
	public Float getTotal() {
		return this.total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}

	@Column(name = "concepto", length = 512)
	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaingreso", length = 0)
	public Date getFechaingreso() {
		return this.fechaingreso;
	}

	public void setFechaingreso(Date fechaingreso) {
		this.fechaingreso = fechaingreso;
	}

	@Column(name = "codigo", length = 512)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

}
