package sarandon.decotheco.thecoradores.bean;
// Generated 16-abr-2017 9:59:59 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Preferences generated by hbm2java
 */
@Entity
@Table(name = "preferences", catalog = "decotheco")
public class Preferences implements java.io.Serializable {

	private Integer id;
	private Projects projects;
	private String habitacion;
	private String estilo;
	private String minimalismo;
	private String color;
	private Date fechaingreso;
	private String idMoodboard;
	private String tiendas;

	public Preferences() {
	}

	public Preferences(Projects projects, String habitacion, String estilo, String minimalismo, String color,
			Date fechaingreso, String idMoodboard, String tiendas) {
		this.projects = projects;
		this.habitacion = habitacion;
		this.estilo = estilo;
		this.minimalismo = minimalismo;
		this.color = color;
		this.fechaingreso = fechaingreso;
		this.idMoodboard = idMoodboard;
		this.tiendas = tiendas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proyecto")
	@JsonBackReference
	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	@Column(name = "habitacion", length = 512)
	public String getHabitacion() {
		return this.habitacion;
	}

	public void setHabitacion(String habitacion) {
		this.habitacion = habitacion;
	}

	@Column(name = "estilo", length = 512)
	public String getEstilo() {
		return this.estilo;
	}

	public void setEstilo(String estilo) {
		this.estilo = estilo;
	}

	@Column(name = "minimalismo", length = 512)
	public String getMinimalismo() {
		return this.minimalismo;
	}

	public void setMinimalismo(String minimalismo) {
		this.minimalismo = minimalismo;
	}

	@Column(name = "color", length = 512)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaingreso", length = 0)
	public Date getFechaingreso() {
		return this.fechaingreso;
	}

	public void setFechaingreso(Date fechaingreso) {
		this.fechaingreso = fechaingreso;
	}

	@Column(name = "id_moodboard", length = 64)
	public String getIdMoodboard() {
		return this.idMoodboard;
	}

	public void setIdMoodboard(String idMoodboard) {
		this.idMoodboard = idMoodboard;
	}

	@Column(name = "tiendas", length = 1024)
	public String getTiendas() {
		return this.tiendas;
	}

	public void setTiendas(String tiendas) {
		this.tiendas = tiendas;
	}

}
