package sarandon.decotheco.thecoradores.bean;
// Generated 26-jul-2017 12:40:51 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProjectsStates generated by hbm2java
 */
@Entity
@Table(name = "projects_states", catalog = "decotheco")
public class ProjectsStates implements java.io.Serializable {

	private int id;
	private String nombre;
	private Integer dias;
	private String turnoDe;
	private Integer componente;
	private String page;
	private String texto_usuarios;
	private String texto_decoradores;
	

	



	public ProjectsStates() {
	}

	public ProjectsStates(int id) {
		this.id = id;
	}

	public ProjectsStates(int id, String nombre, Integer dias, String turnoDe, Integer componente, String page
			) {
		this.id = id;
		this.nombre = nombre;
		this.dias = dias;
		this.turnoDe = turnoDe;
		this.componente = componente;
		this.page = page;
		
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 512)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "dias")
	public Integer getDias() {
		return this.dias;
	}

	public void setDias(Integer dias) {
		this.dias = dias;
	}

	@Column(name = "turno_de", length = 45)
	public String getTurnoDe() {
		return this.turnoDe;
	}

	public void setTurnoDe(String turnoDe) {
		this.turnoDe = turnoDe;
	}

	@Column(name = "componente")
	public Integer getComponente() {
		return this.componente;
	}

	public void setComponente(Integer componente) {
		this.componente = componente;
	}

	@Column(name = "page", length = 512)
	public String getPage() {
		return this.page;
	}

	public void setPage(String page) {
		this.page = page;
	}
	
	
	@Column(name = "texto_decoradores", length = 512)
	public String getTexto_decoradores() {
		return texto_decoradores;
	}
	@Column(name = "texto_usuarios", length = 512)
	public String getTexto_usuarios() {
		return texto_usuarios;
	}

	public void setTexto_decoradores(String texto_decoradores) {
		this.texto_decoradores = texto_decoradores;
	}

	public void setTexto_usuarios(String texto_usuarios) {
		this.texto_usuarios = texto_usuarios;
	}
	
}

