package sarandon.decotheco.thecoradores.bean;
// Generated 26-jul-2017 12:40:51 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProjectsTypes generated by hbm2java
 */
@Entity
@Table(name = "projects_types", catalog = "decotheco")
public class ProjectsTypes implements java.io.Serializable {

	private Integer id;
	private String nombreProyecto;
	private Float precio;
	private Integer fee;
	private Float baseImponible;
	private Set<Projects> projectses = new HashSet<Projects>(0);
	private Set<AuxTypesStates> auxTypesStateses = new HashSet<AuxTypesStates>(0);

	public ProjectsTypes() {
	}

	public ProjectsTypes(String nombreProyecto, Float precio, Set<Projects> projectses,
			Set<AuxTypesStates> auxTypesStateses, Float base) {
		this.nombreProyecto = nombreProyecto;
		this.precio = precio;
		this.projectses = projectses;
		this.baseImponible = base;
		this.auxTypesStateses = auxTypesStateses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre_proyecto", length = 45)
	public String getNombreProyecto() {
		return this.nombreProyecto;
	}

	public void setNombreProyecto(String nombreProyecto) {
		this.nombreProyecto = nombreProyecto;
	}

	@Column(name = "precio", precision = 12, scale = 0)
	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectsTypes")
	public Set<Projects> getProjectses() {
		return this.projectses;
	}

	public void setProjectses(Set<Projects> projectses) {
		this.projectses = projectses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectsTypes")
	public Set<AuxTypesStates> getAuxTypesStateses() {
		return this.auxTypesStateses;
	}

	public void setAuxTypesStateses(Set<AuxTypesStates> auxTypesStateses) {
		this.auxTypesStateses = auxTypesStateses;
	}
	public Integer getFee() {
		return fee;
	}

	public void setFee(Integer fee) {
		this.fee = fee;
	}
	
	public void setBase(Float base_imponible) {
		this.baseImponible = base_imponible;
	}
	

}

